// Generated by scripts/generate-blog-catalog.mjs. Do not edit.
//
// Every handle a retired `?post=` URL could carry - each language's slug and
// the article's translation key - mapped to the slug that article is published
// under in each language. See the comment in the generator for why this cannot
// be computed from the incoming slug.

export const ARTICLE_SLUGS: Record<string, Partial<Record<string, string>>> = {
  "a-psicologia-das-decisoes-de-dinheiro-por-que-saber-as-contas-nao-basta": {
    "en": "the-psychology-of-money-decisions-why-knowing-the-maths-is-not-enough",
    "es": "la-psicologia-de-las-decisiones-de-dinero-por-que-saber-las-cuentas-no-basta",
    "pt": "a-psicologia-das-decisoes-de-dinheiro-por-que-saber-as-contas-nao-basta"
  },
  "aumenta-tu-productividad-diaria-con-herramientas-de-lean-management": {
    "en": "boost-your-daily-productivity-with-lean-management-tools",
    "es": "aumenta-tu-productividad-diaria-con-herramientas-de-lean-management",
    "pt": "aumente-sua-produtividade-diaria-com-ferramentas-de-lean-management"
  },
  "aumente-sua-produtividade-diaria-com-ferramentas-de-lean-management": {
    "en": "boost-your-daily-productivity-with-lean-management-tools",
    "es": "aumenta-tu-productividad-diaria-con-herramientas-de-lean-management",
    "pt": "aumente-sua-produtividade-diaria-com-ferramentas-de-lean-management"
  },
  "boost-your-daily-productivity-with-lean-management-tools": {
    "en": "boost-your-daily-productivity-with-lean-management-tools",
    "es": "aumenta-tu-productividad-diaria-con-herramientas-de-lean-management",
    "pt": "aumente-sua-produtividade-diaria-com-ferramentas-de-lean-management"
  },
  "building-wealth-good-financial-habits": {
    "en": "building-wealth-through-good-financial-habits-key-lessons-from-rich-dad-poor-dad",
    "es": "como-crear-riqueza-con-buenos-habitos-financieros-lecciones-de-padre-rico-padre-pobre",
    "pt": "como-construir-riqueza-com-bons-habitos-financeiros-licoes-de-pai-rico-pai-pobre"
  },
  "building-wealth-through-good-financial-habits-key-lessons-from-rich-dad-poor-dad": {
    "en": "building-wealth-through-good-financial-habits-key-lessons-from-rich-dad-poor-dad",
    "es": "como-crear-riqueza-con-buenos-habitos-financieros-lecciones-de-padre-rico-padre-pobre",
    "pt": "como-construir-riqueza-com-bons-habitos-financeiros-licoes-de-pai-rico-pai-pobre"
  },
  "century-of-market-history": {
    "en": "what-a-century-of-market-history-teaches-drawdowns-recovery-and-diversification",
    "es": "que-ensena-un-siglo-de-historia-de-los-mercados-caidas-recuperacion-y-diversificacion",
    "pt": "o-que-ensina-um-seculo-de-historia-dos-mercados-quedas-recuperacao-e-diversificacao"
  },
  "como-construir-riqueza-com-bons-habitos-financeiros-licoes-de-pai-rico-pai-pobre": {
    "en": "building-wealth-through-good-financial-habits-key-lessons-from-rich-dad-poor-dad",
    "es": "como-crear-riqueza-con-buenos-habitos-financieros-lecciones-de-padre-rico-padre-pobre",
    "pt": "como-construir-riqueza-com-bons-habitos-financeiros-licoes-de-pai-rico-pai-pobre"
  },
  "como-crear-riqueza-con-buenos-habitos-financieros-lecciones-de-padre-rico-padre-pobre": {
    "en": "building-wealth-through-good-financial-habits-key-lessons-from-rich-dad-poor-dad",
    "es": "como-crear-riqueza-con-buenos-habitos-financieros-lecciones-de-padre-rico-padre-pobre",
    "pt": "como-construir-riqueza-com-bons-habitos-financeiros-licoes-de-pai-rico-pai-pobre"
  },
  "debt-management-how-to-get-out-and-stay-out-of-debt": {
    "en": "debt-management-how-to-get-out-and-stay-out-of-debt",
    "es": "gestion-de-deudas-como-salir-y-mantenerte-fuera-de-ellas",
    "pt": "gestao-de-dividas-como-sair-e-manter-se-livre-das-dividas"
  },
  "estructura-y-maquinaria-operativa-de-las-instituciones-de-inversion-colectiva-iic": {
    "en": "how-collective-investment-schemes-work-inside-the-machinery-of-mutual-funds",
    "es": "estructura-y-maquinaria-operativa-de-las-instituciones-de-inversion-colectiva-iic",
    "pt": "estrutura-e-maquinaria-operacional-dos-organismos-de-investimento-coletivo-oic"
  },
  "estrutura-e-maquinaria-operacional-dos-organismos-de-investimento-coletivo-oic": {
    "en": "how-collective-investment-schemes-work-inside-the-machinery-of-mutual-funds",
    "es": "estructura-y-maquinaria-operativa-de-las-instituciones-de-inversion-colectiva-iic",
    "pt": "estrutura-e-maquinaria-operacional-dos-organismos-de-investimento-coletivo-oic"
  },
  "foundations-of-personal-finance-how-to-control-expenses-and-build-wealth": {
    "en": "foundations-of-personal-finance-how-to-control-expenses-and-build-wealth",
    "es": "fundamentos-de-las-finanzas-personales-como-controlar-gastos-y-crear-riqueza",
    "pt": "fundamentos-das-financas-pessoais-como-controlar-despesas-e-criar-riqueza"
  },
  "foundations-personal-finance-controlling-expenses": {
    "en": "foundations-of-personal-finance-how-to-control-expenses-and-build-wealth",
    "es": "fundamentos-de-las-finanzas-personales-como-controlar-gastos-y-crear-riqueza",
    "pt": "fundamentos-das-financas-pessoais-como-controlar-despesas-e-criar-riqueza"
  },
  "four-passive-income-engines": {
    "en": "passive-income-is-not-one-thing-four-engines-and-what-each-one-costs",
    "es": "los-ingresos-pasivos-no-son-una-sola-cosa-cuatro-motores-y-lo-que-cuesta-cada-uno",
    "pt": "rendimento-passivo-nao-e-uma-so-coisa-quatro-motores-e-o-que-cada-um-custa"
  },
  "fundamentos-das-financas-pessoais-como-controlar-despesas-e-criar-riqueza": {
    "en": "foundations-of-personal-finance-how-to-control-expenses-and-build-wealth",
    "es": "fundamentos-de-las-finanzas-personales-como-controlar-gastos-y-crear-riqueza",
    "pt": "fundamentos-das-financas-pessoais-como-controlar-despesas-e-criar-riqueza"
  },
  "fundamentos-de-las-finanzas-personales-como-controlar-gastos-y-crear-riqueza": {
    "en": "foundations-of-personal-finance-how-to-control-expenses-and-build-wealth",
    "es": "fundamentos-de-las-finanzas-personales-como-controlar-gastos-y-crear-riqueza",
    "pt": "fundamentos-das-financas-pessoais-como-controlar-despesas-e-criar-riqueza"
  },
  "gastar-com-proposito-como-alinhar-o-seu-dinheiro-com-o-que-realmente-importa": {
    "en": "spending-with-purpose-how-to-align-your-money-with-what-truly-matters",
    "es": "gastar-con-proposito-como-alinear-tu-dinero-con-lo-que-realmente-importa",
    "pt": "gastar-com-proposito-como-alinhar-o-seu-dinheiro-com-o-que-realmente-importa"
  },
  "gastar-con-proposito-como-alinear-tu-dinero-con-lo-que-realmente-importa": {
    "en": "spending-with-purpose-how-to-align-your-money-with-what-truly-matters",
    "es": "gastar-con-proposito-como-alinear-tu-dinero-con-lo-que-realmente-importa",
    "pt": "gastar-com-proposito-como-alinhar-o-seu-dinheiro-com-o-que-realmente-importa"
  },
  "gestao-de-dividas-como-sair-e-manter-se-livre-das-dividas": {
    "en": "debt-management-how-to-get-out-and-stay-out-of-debt",
    "es": "gestion-de-deudas-como-salir-y-mantenerte-fuera-de-ellas",
    "pt": "gestao-de-dividas-como-sair-e-manter-se-livre-das-dividas"
  },
  "gestion-de-deudas-como-salir-y-mantenerte-fuera-de-ellas": {
    "en": "debt-management-how-to-get-out-and-stay-out-of-debt",
    "es": "gestion-de-deudas-como-salir-y-mantenerte-fuera-de-ellas",
    "pt": "gestao-de-dividas-como-sair-e-manter-se-livre-das-dividas"
  },
  "how-collective-investment-schemes-work-inside-the-machinery-of-mutual-funds": {
    "en": "how-collective-investment-schemes-work-inside-the-machinery-of-mutual-funds",
    "es": "estructura-y-maquinaria-operativa-de-las-instituciones-de-inversion-colectiva-iic",
    "pt": "estrutura-e-maquinaria-operacional-dos-organismos-de-investimento-coletivo-oic"
  },
  "inversion-para-principiantes-guia-basica-para-hacer-crecer-tu-dinero": {
    "en": "investing-101-a-beginner-s-guide-to-growing-your-wealth",
    "es": "inversion-para-principiantes-guia-basica-para-hacer-crecer-tu-dinero",
    "pt": "investimento-para-iniciantes-guia-basico-para-fazer-crescer-o-seu-patrimonio"
  },
  "investimento-para-iniciantes-guia-basico-para-fazer-crescer-o-seu-patrimonio": {
    "en": "investing-101-a-beginner-s-guide-to-growing-your-wealth",
    "es": "inversion-para-principiantes-guia-basica-para-hacer-crecer-tu-dinero",
    "pt": "investimento-para-iniciantes-guia-basico-para-fazer-crescer-o-seu-patrimonio"
  },
  "investing-101-a-beginner-s-guide-to-growing-your-wealth": {
    "en": "investing-101-a-beginner-s-guide-to-growing-your-wealth",
    "es": "inversion-para-principiantes-guia-basica-para-hacer-crecer-tu-dinero",
    "pt": "investimento-para-iniciantes-guia-basico-para-fazer-crescer-o-seu-patrimonio"
  },
  "investing-101-beginners-guide-to-growing-wealth": {
    "en": "investing-101-a-beginner-s-guide-to-growing-your-wealth",
    "es": "inversion-para-principiantes-guia-basica-para-hacer-crecer-tu-dinero",
    "pt": "investimento-para-iniciantes-guia-basico-para-fazer-crescer-o-seu-patrimonio"
  },
  "investment-limits-and-risk-diversification-in-mutual-funds-ucits": {
    "en": "investment-limits-and-risk-diversification-in-mutual-funds-ucits",
    "es": "limites-de-inversion-y-diversificacion-del-riesgo-en-instituciones-de-inversion-colectiva-ucits",
    "pt": "limites-de-investimento-e-diversificacao-de-risco-em-organismos-de-investimento-coletivo-ucits"
  },
  "la-psicologia-de-las-decisiones-de-dinero-por-que-saber-las-cuentas-no-basta": {
    "en": "the-psychology-of-money-decisions-why-knowing-the-maths-is-not-enough",
    "es": "la-psicologia-de-las-decisiones-de-dinero-por-que-saber-las-cuentas-no-basta",
    "pt": "a-psicologia-das-decisoes-de-dinheiro-por-que-saber-as-contas-nao-basta"
  },
  "limites-de-inversion-y-diversificacion-del-riesgo-en-instituciones-de-inversion-colectiva-ucits": {
    "en": "investment-limits-and-risk-diversification-in-mutual-funds-ucits",
    "es": "limites-de-inversion-y-diversificacion-del-riesgo-en-instituciones-de-inversion-colectiva-ucits",
    "pt": "limites-de-investimento-e-diversificacao-de-risco-em-organismos-de-investimento-coletivo-ucits"
  },
  "limites-de-investimento-e-diversificacao-de-risco-em-organismos-de-investimento-coletivo-ucits": {
    "en": "investment-limits-and-risk-diversification-in-mutual-funds-ucits",
    "es": "limites-de-inversion-y-diversificacion-del-riesgo-en-instituciones-de-inversion-colectiva-ucits",
    "pt": "limites-de-investimento-e-diversificacao-de-risco-em-organismos-de-investimento-coletivo-ucits"
  },
  "los-ingresos-pasivos-no-son-una-sola-cosa-cuatro-motores-y-lo-que-cuesta-cada-uno": {
    "en": "passive-income-is-not-one-thing-four-engines-and-what-each-one-costs",
    "es": "los-ingresos-pasivos-no-son-una-sola-cosa-cuatro-motores-y-lo-que-cuesta-cada-uno",
    "pt": "rendimento-passivo-nao-e-uma-so-coisa-quatro-motores-e-o-que-cada-um-custa"
  },
  "o-que-ensina-um-seculo-de-historia-dos-mercados-quedas-recuperacao-e-diversificacao": {
    "en": "what-a-century-of-market-history-teaches-drawdowns-recovery-and-diversification",
    "es": "que-ensena-un-siglo-de-historia-de-los-mercados-caidas-recuperacion-y-diversificacion",
    "pt": "o-que-ensina-um-seculo-de-historia-dos-mercados-quedas-recuperacao-e-diversificacao"
  },
  "o-que-o-nome-do-seu-fundo-esconde-categorias-de-investimento-e-regras-regulatorias": {
    "en": "what-your-fund-s-name-is-hiding-investment-mandates-and-regulatory-categories",
    "es": "que-ocultan-los-nombres-de-tus-fondos-vocaciones-inversoras-y-clasificacion-regulatoria",
    "pt": "o-que-o-nome-do-seu-fundo-esconde-categorias-de-investimento-e-regras-regulatorias"
  },
  "pagate-a-ti-mismo-primero-el-habito-clave-para-crear-riqueza": {
    "en": "pay-yourself-first-the-simple-habit-to-build-lasting-wealth",
    "es": "pagate-a-ti-mismo-primero-el-habito-clave-para-crear-riqueza",
    "pt": "pague-se-a-si-mesmo-primeiro-o-habito-chave-para-criar-riqueza"
  },
  "pague-se-a-si-mesmo-primeiro-o-habito-chave-para-criar-riqueza": {
    "en": "pay-yourself-first-the-simple-habit-to-build-lasting-wealth",
    "es": "pagate-a-ti-mismo-primero-el-habito-clave-para-crear-riqueza",
    "pt": "pague-se-a-si-mesmo-primeiro-o-habito-chave-para-criar-riqueza"
  },
  "passive-income-is-not-one-thing-four-engines-and-what-each-one-costs": {
    "en": "passive-income-is-not-one-thing-four-engines-and-what-each-one-costs",
    "es": "los-ingresos-pasivos-no-son-una-sola-cosa-cuatro-motores-y-lo-que-cuesta-cada-uno",
    "pt": "rendimento-passivo-nao-e-uma-so-coisa-quatro-motores-e-o-que-cada-um-custa"
  },
  "pay-yourself-first-power-of-saving": {
    "en": "pay-yourself-first-the-simple-habit-to-build-lasting-wealth",
    "es": "pagate-a-ti-mismo-primero-el-habito-clave-para-crear-riqueza",
    "pt": "pague-se-a-si-mesmo-primeiro-o-habito-chave-para-criar-riqueza"
  },
  "pay-yourself-first-the-simple-habit-to-build-lasting-wealth": {
    "en": "pay-yourself-first-the-simple-habit-to-build-lasting-wealth",
    "es": "pagate-a-ti-mismo-primero-el-habito-clave-para-crear-riqueza",
    "pt": "pague-se-a-si-mesmo-primeiro-o-habito-chave-para-criar-riqueza"
  },
  "planeja-sua-aposentadoria-guia-pratico-para-garantir-seu-futuro": {
    "en": "retirement-planning-101-how-to-secure-your-future",
    "es": "planifica-tu-jubilacion-guia-basica-para-asegurar-tu-futuro",
    "pt": "planeja-sua-aposentadoria-guia-pratico-para-garantir-seu-futuro"
  },
  "planifica-tu-jubilacion-guia-basica-para-asegurar-tu-futuro": {
    "en": "retirement-planning-101-how-to-secure-your-future",
    "es": "planifica-tu-jubilacion-guia-basica-para-asegurar-tu-futuro",
    "pt": "planeja-sua-aposentadoria-guia-pratico-para-garantir-seu-futuro"
  },
  "poner-tu-dinero-a-trabajar-genera-ingresos-mientras-duermes": {
    "en": "putting-your-money-to-work-make-money-while-you-sleep",
    "es": "poner-tu-dinero-a-trabajar-genera-ingresos-mientras-duermes",
    "pt": "por-seu-dinheiro-a-trabalhar-faca-dinheiro-enquanto-dorme"
  },
  "por-que-los-fondos-operan-a-ciegas-mecanica-de-suscripciones-reembolsos-y-valor-liquidativo": {
    "en": "why-mutual-funds-operate-blind-the-mechanics-of-subscriptions-redemptions-and-nav",
    "es": "por-que-los-fondos-operan-a-ciegas-mecanica-de-suscripciones-reembolsos-y-valor-liquidativo",
    "pt": "por-que-os-fundos-operam-as-cegas-a-mecanica-de-subscricoes-resgates-e-valor-da-cota"
  },
  "por-que-os-fundos-operam-as-cegas-a-mecanica-de-subscricoes-resgates-e-valor-da-cota": {
    "en": "why-mutual-funds-operate-blind-the-mechanics-of-subscriptions-redemptions-and-nav",
    "es": "por-que-los-fondos-operan-a-ciegas-mecanica-de-suscripciones-reembolsos-y-valor-liquidativo",
    "pt": "por-que-os-fundos-operam-as-cegas-a-mecanica-de-subscricoes-resgates-e-valor-da-cota"
  },
  "por-seu-dinheiro-a-trabalhar-faca-dinheiro-enquanto-dorme": {
    "en": "putting-your-money-to-work-make-money-while-you-sleep",
    "es": "poner-tu-dinero-a-trabajar-genera-ingresos-mientras-duermes",
    "pt": "por-seu-dinheiro-a-trabalhar-faca-dinheiro-enquanto-dorme"
  },
  "putting-your-money-to-work-make-money-while-you-sleep": {
    "en": "putting-your-money-to-work-make-money-while-you-sleep",
    "es": "poner-tu-dinero-a-trabajar-genera-ingresos-mientras-duermes",
    "pt": "por-seu-dinheiro-a-trabalhar-faca-dinheiro-enquanto-dorme"
  },
  "que-ensena-un-siglo-de-historia-de-los-mercados-caidas-recuperacion-y-diversificacion": {
    "en": "what-a-century-of-market-history-teaches-drawdowns-recovery-and-diversification",
    "es": "que-ensena-un-siglo-de-historia-de-los-mercados-caidas-recuperacion-y-diversificacion",
    "pt": "o-que-ensina-um-seculo-de-historia-dos-mercados-quedas-recuperacao-e-diversificacao"
  },
  "que-ocultan-los-nombres-de-tus-fondos-vocaciones-inversoras-y-clasificacion-regulatoria": {
    "en": "what-your-fund-s-name-is-hiding-investment-mandates-and-regulatory-categories",
    "es": "que-ocultan-los-nombres-de-tus-fondos-vocaciones-inversoras-y-clasificacion-regulatoria",
    "pt": "o-que-o-nome-do-seu-fundo-esconde-categorias-de-investimento-e-regras-regulatorias"
  },
  "rendimento-passivo-nao-e-uma-so-coisa-quatro-motores-e-o-que-cada-um-custa": {
    "en": "passive-income-is-not-one-thing-four-engines-and-what-each-one-costs",
    "es": "los-ingresos-pasivos-no-son-una-sola-cosa-cuatro-motores-y-lo-que-cuesta-cada-uno",
    "pt": "rendimento-passivo-nao-e-uma-so-coisa-quatro-motores-e-o-que-cada-um-custa"
  },
  "retirement-planning-101-how-to-secure-your-future": {
    "en": "retirement-planning-101-how-to-secure-your-future",
    "es": "planifica-tu-jubilacion-guia-basica-para-asegurar-tu-futuro",
    "pt": "planeja-sua-aposentadoria-guia-pratico-para-garantir-seu-futuro"
  },
  "riesgo-de-secuencia-de-rentabilidades-por-que-el-orden-decide-tu-jubilacion": {
    "en": "sequence-of-returns-risk-why-the-order-of-returns-decides-your-retirement",
    "es": "riesgo-de-secuencia-de-rentabilidades-por-que-el-orden-decide-tu-jubilacion",
    "pt": "risco-de-sequencia-por-que-a-ordem-das-rentabilidades-decide-a-sua-aposentadoria"
  },
  "risco-de-sequencia-por-que-a-ordem-das-rentabilidades-decide-a-sua-aposentadoria": {
    "en": "sequence-of-returns-risk-why-the-order-of-returns-decides-your-retirement",
    "es": "riesgo-de-secuencia-de-rentabilidades-por-que-el-orden-decide-tu-jubilacion",
    "pt": "risco-de-sequencia-por-que-a-ordem-das-rentabilidades-decide-a-sua-aposentadoria"
  },
  "sequence-of-returns-risk": {
    "en": "sequence-of-returns-risk-why-the-order-of-returns-decides-your-retirement",
    "es": "riesgo-de-secuencia-de-rentabilidades-por-que-el-orden-decide-tu-jubilacion",
    "pt": "risco-de-sequencia-por-que-a-ordem-das-rentabilidades-decide-a-sua-aposentadoria"
  },
  "sequence-of-returns-risk-why-the-order-of-returns-decides-your-retirement": {
    "en": "sequence-of-returns-risk-why-the-order-of-returns-decides-your-retirement",
    "es": "riesgo-de-secuencia-de-rentabilidades-por-que-el-orden-decide-tu-jubilacion",
    "pt": "risco-de-sequencia-por-que-a-ordem-das-rentabilidades-decide-a-sua-aposentadoria"
  },
  "sistema-dinero-lento": {
    "en": "slow-money-system",
    "es": "sistema-dinero-lento",
    "pt": "sistema-dinheiro-lento"
  },
  "sistema-dinheiro-lento": {
    "en": "slow-money-system",
    "es": "sistema-dinero-lento",
    "pt": "sistema-dinheiro-lento"
  },
  "slow-money-system": {
    "en": "slow-money-system",
    "es": "sistema-dinero-lento",
    "pt": "sistema-dinheiro-lento"
  },
  "spending-with-purpose-align-money-values": {
    "en": "spending-with-purpose-how-to-align-your-money-with-what-truly-matters",
    "es": "gastar-con-proposito-como-alinear-tu-dinero-con-lo-que-realmente-importa",
    "pt": "gastar-com-proposito-como-alinhar-o-seu-dinheiro-com-o-que-realmente-importa"
  },
  "spending-with-purpose-how-to-align-your-money-with-what-truly-matters": {
    "en": "spending-with-purpose-how-to-align-your-money-with-what-truly-matters",
    "es": "gastar-con-proposito-como-alinear-tu-dinero-con-lo-que-realmente-importa",
    "pt": "gastar-com-proposito-como-alinhar-o-seu-dinheiro-com-o-que-realmente-importa"
  },
  "the-psychology-of-money-decisions-why-knowing-the-maths-is-not-enough": {
    "en": "the-psychology-of-money-decisions-why-knowing-the-maths-is-not-enough",
    "es": "la-psicologia-de-las-decisiones-de-dinero-por-que-saber-las-cuentas-no-basta",
    "pt": "a-psicologia-das-decisoes-de-dinheiro-por-que-saber-as-contas-nao-basta"
  },
  "transferring-funds-tax-deferred-fiscal-deferral-snce-infrastructure": {
    "es": "traspasar-fondos-sin-pagar-a-hacienda-mecanica-del-diferimiento-fiscal-y-la-infraestructura-del-snce"
  },
  "traspasar-fondos-sin-pagar-a-hacienda-mecanica-del-diferimiento-fiscal-y-la-infraestructura-del-snce": {
    "es": "traspasar-fondos-sin-pagar-a-hacienda-mecanica-del-diferimiento-fiscal-y-la-infraestructura-del-snce"
  },
  "what-a-century-of-market-history-teaches-drawdowns-recovery-and-diversification": {
    "en": "what-a-century-of-market-history-teaches-drawdowns-recovery-and-diversification",
    "es": "que-ensena-un-siglo-de-historia-de-los-mercados-caidas-recuperacion-y-diversificacion",
    "pt": "o-que-ensina-um-seculo-de-historia-dos-mercados-quedas-recuperacao-e-diversificacao"
  },
  "what-your-fund-s-name-is-hiding-investment-mandates-and-regulatory-categories": {
    "en": "what-your-fund-s-name-is-hiding-investment-mandates-and-regulatory-categories",
    "es": "que-ocultan-los-nombres-de-tus-fondos-vocaciones-inversoras-y-clasificacion-regulatoria",
    "pt": "o-que-o-nome-do-seu-fundo-esconde-categorias-de-investimento-e-regras-regulatorias"
  },
  "what-your-funds-name-is-hiding-investment-mandates-and-regulatory-categories": {
    "en": "what-your-fund-s-name-is-hiding-investment-mandates-and-regulatory-categories",
    "es": "que-ocultan-los-nombres-de-tus-fondos-vocaciones-inversoras-y-clasificacion-regulatoria",
    "pt": "o-que-o-nome-do-seu-fundo-esconde-categorias-de-investimento-e-regras-regulatorias"
  },
  "why-knowing-the-maths-is-not-enough": {
    "en": "the-psychology-of-money-decisions-why-knowing-the-maths-is-not-enough",
    "es": "la-psicologia-de-las-decisiones-de-dinero-por-que-saber-las-cuentas-no-basta",
    "pt": "a-psicologia-das-decisoes-de-dinheiro-por-que-saber-as-contas-nao-basta"
  },
  "why-mutual-funds-operate-blind-mechanics-of-subscriptions-redemptions-and-nav": {
    "en": "why-mutual-funds-operate-blind-the-mechanics-of-subscriptions-redemptions-and-nav",
    "es": "por-que-los-fondos-operan-a-ciegas-mecanica-de-suscripciones-reembolsos-y-valor-liquidativo",
    "pt": "por-que-os-fundos-operam-as-cegas-a-mecanica-de-subscricoes-resgates-e-valor-da-cota"
  },
  "why-mutual-funds-operate-blind-the-mechanics-of-subscriptions-redemptions-and-nav": {
    "en": "why-mutual-funds-operate-blind-the-mechanics-of-subscriptions-redemptions-and-nav",
    "es": "por-que-los-fondos-operan-a-ciegas-mecanica-de-suscripciones-reembolsos-y-valor-liquidativo",
    "pt": "por-que-os-fundos-operam-as-cegas-a-mecanica-de-subscricoes-resgates-e-valor-da-cota"
  }
};
